### ISSUE TITLE
"【News】SDK Memory Optimization - Save 8k SRAM!（SDK 内存优化更新）"

### ISSUE THREAD

**Issue by eriksl** [pfalcon/esp-open-sdk#70] opened 2015-07-22 08:48 UTC
Can you please incorporate this?

http://bbs.espressif.com/viewtopic.php?f=5&t=743

**Comment by pfalcon** [comment] 2015-07-22 09:09
Duplicate of #67, #68.

**Closed by pfalcon** 2015-07-22 09:09 UTC

**Comment by eriksl** [comment] 2015-07-22 16:52
Sorry I didn't see it, must be in need of glasses apparently ;-)

**Comment by pfalcon** [comment] 2015-07-22 18:27
Nope, just feel free to check already submitted bugs before posting new ;-).

**Comment by eriksl** [comment] 2015-07-22 18:52
What happened, I think, is that I checked the issues, not the pull requests. It looks to me like the issues already active were actually pull requests. But never mind, I'll check them too in the future.
